### ISSUE TITLE
Training time for the SMD dataset is too long

### ISSUE THREAD

**Issue by WeixuWang** [DAMO-DI-ML/KDD2023-DCdetector#13]
As mentioned in the paper, when the d_model size is set as 256, the average running time of 100 iterations is less than 0.2s. However, when I set batch size=32 and d_model=256, the duration of each iteration is 3~4s, which is much slower. The GPU I am using is 3090, is there any problem with the parameter settings?

![image](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/assets/74447165/531c7833-e3c7-4d3b-b900-462d1b4093b2)

**Comment by tianzhou2011** [comment]
check the script, we use "export CUDA_VISIBLE_DEVICES=3", If you have only one GPU, change it to 0

**Comment by stillwang96** [comment]
> As mentioned in the paper, when the d_model size is set as 256, the average running time of 100 iterations is less than 0.2s. However, when I set batch size=32 and d_model=256, the duration of each iteration is 3~4s, which is much slower. The GPU I am using is 3090, is there any problem with the parameter settings?
> 
> ![image](https://user-images.githubusercontent.com/74447165/262523175-531c7833-e3c7-4d3b-b900-462d1b4093b2.png)

Hi, my GPU is 3090 too, and I don't know whether the running time of mine is normal. Please help me check it if you have changed your GPU to 0. Thank you.

================ Hyperparameters ===============
anormly_ratio: 0.6
batch_size: 256
d_model: 256
data_path: SMD
dataset: SMD
device_ids: [0, 1, 2, 3]
devices: 0,1,2,3
e_layers: 3
gpu: 0
index: 137
input_c: 38
k: 3
loss_fuc: MSE
lr: 0.0001
mode: train
model_save_path: checkpoints
n_heads: 1
num_epochs: 2
output_c: 38
patch_size: [5, 7]
rec_timeseries: True
use_gpu: True
use_multi_gpu: True
win_size: 105
====================  Train  ===================
        speed: 0.5840s/iter; left time: 3172.7369s
        speed: 0.5829s/iter; left time: 3108.4683s
        speed: 0.5827s/iter; left time: 3049.0521s
        speed: 0.5852s/iter; left time: 3004.0091s
        speed: 0.5883s/iter; left time: 2961.1121s
        speed: 0.5838s/iter; left time: 2880.1116s
        speed: 0.5809s/iter; left time: 2807.3317s
