### ISSUE TITLE
There are some errors in the parameter order when using the evaluation function

### ISSUE THREAD

**Issue by zhangsunny** [DAMO-DI-ML/KDD2023-DCdetector#36]
In [solver.py Line 304](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/solver.py#L304), 
`scores_simple = combine_all_evaluation_scores(pred, gt, test_energy)`, the first parameter is predicted label, and the second one is ground truth. But according to the definition of `combine_all_evaluation_scores(y_test, pred_labels, anomaly_scores)` in [combine_all_scores.py Line 14](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/metrics/combine_all_scores.py#L14), the first required parameter is `y_test` the true label, and the second one `pred_labels` is the predicion.

And, in [combine_all_evaluation_scores Line 22](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/metrics/combine_all_scores.py#L22), the inputs of `get_adjust_F1PA(y_test, pred_labels)` are ground truths and predictions, while according to the definition of [get_adjust_F1PA](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/metrics/f1_score_f1_pa.py#L27), `def get_adjust_F1PA(pred, gt)` the inputs are predictions and ground truths.

**So, coincidentally, the point-adjusted evalution results are correct, but other scores (e.g., Affiliation, VUS, AUC) seem wrong.**

**Comment by yyysjz1997** [comment]
> In [solver.py Line 304](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/solver.py#L304), `scores_simple = combine_all_evaluation_scores(pred, gt, test_energy)`, the first parameter is predicted label, and the second one is ground truth. But according to the definition of `combine_all_evaluation_scores(y_test, pred_labels, anomaly_scores)` in [combine_all_scores.py Line 14](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/metrics/combine_all_scores.py#L14), the first required parameter is `y_test` the true label, and the second one `pred_labels` is the predicion.
> 
> And, in [combine_all_evaluation_scores Line 22](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/metrics/combine_all_scores.py#L22), the inputs of `get_adjust_F1PA(y_test, pred_labels)` are ground truths and predictions, while according to the definition of [get_adjust_F1PA](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/9d107cae518ef24ee2eb2ad1b92107cdcd09ea10/metrics/f1_score_f1_pa.py#L27), `def get_adjust_F1PA(pred, gt)` the inputs are predictions and ground truths.
> 
> **So, coincidentally, the point-adjusted evalution results are correct, but other scores (e.g., Affiliation, VUS, AUC) seem wrong.**

Hi, in `combine_all_evaluation_scores(y_test, pred_labels, anomaly_scores)`, the first parameter indicates the predicted value and the second parameter indicates the true label. Sorry if our parameter definitions have caused you to misunderstand. But it seems that the results are fine.
