### ISSUE TITLE
Inquiry Regarding Suitability for Anomaly Detection

### ISSUE THREAD

**Issue by 7C00-lee** [DAMO-DI-ML/KDD2023-DCdetector#37]
Hello, I hope this message finds you well. I wanted to take a moment to express my sincere gratitude for your valuable contributions to DCdetector.

Could you kindly provide your perspective on whether your approach would be effective in detecting anomalies in the described context? Any guidance or recommendations you can offer would be greatly appreciated.

Problem description: Extract variable groups with a certain linear relationship from the data.

For example: there are 100 variables (x1 - x100), record the variable values of all variables at 100 timestamps (t1 - t100), which is a 100*100 matrix. And have a matrix that satisfies a certain relationship and a matrix that does not satisfy this relationship. The schematic diagram is as follows:

![image-20240420104437035](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/assets/118035275/2a6cafea-318c-441c-ba7f-da62e1a93afd)

In the figure above, data 1 satisfies the relationship x3+x98 > x1+x2 from t1 to t100, while data 2 has moments when it does not satisfy this relationship (t5 - t100).

Purpose: Given the above two types of data, we can analyze which variables have a certain relationship in data 1. However, this relationship is not completely satisfied in data 2. The specific relationship does not need to be given, only the variable group is given.

It's possible that there are other variables with anomalies present simultaneously, but our aim is to capture sets containing (x1, x2, x3, x98), even if we may capture incorrect answers like (x1, x2, x3, x98, x5, x10) and (x11, x12, x13, x8, x5, x10). 

Thank you for your attention to this matter. I look forward to hearing from you.

中文描述：
问题描述：从数据中提取出具有某种线性关系的变量组。

例如：有100个变量（x1 - x100），记录所有变量在100个时间戳（t1 - t100）的变量值，即为100*100的矩阵。并拥有满足某种关系的矩阵和不满足这种关系的矩阵，示意图如下：

![image](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/assets/118035275/6c79ca8f-0673-4c8c-9769-9576adc522ab)

上图中，数据1在 t1 -t100 中均满足 x3+x98 > x1+x2 这一关系，而数据 2 有不满足该关系的时刻（t5 - t100）

目的：给出上述两种类型的数据，能够分析出哪些变量间在数据1存在某种关系。而在数据2中不完全满足该关系，具体是什么关系可以不给出，只需给出变量组。

可能还有其他变量同时存在异常，但我们的目标是捕获包含 (x1, x2, x3, x98) 的集合，即使我们可能捕获错误的答案，例如 (x1, x2, x3, x98, x5, x10 ）和（x11、x12、x13、x8、x5、x10）。

感谢您的关注。 期待您的回复。

**Comment by yyysjz1997** [comment]
> Hello, I hope this message finds you well. I wanted to take a moment to express my sincere gratitude for your valuable contributions to DCdetector.
> 
> Could you kindly provide your perspective on whether your approach would be effective in detecting anomalies in the described context? Any guidance or recommendations you can offer would be greatly appreciated.
> 
> Problem description: Extract variable groups with a certain linear relationship from the data.
> 
> For example: there are 100 variables (x1 - x100), record the variable values of all variables at 100 timestamps (t1 - t100), which is a 100*100 matrix. And have a matrix that satisfies a certain relationship and a matrix that does not satisfy this relationship. The schematic diagram is as follows:
> 
> ![image-20240420104437035](https://private-user-images.githubusercontent.com/118035275/325067768-2a6cafea-318c-441c-ba7f-da62e1a93afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDU5NTksIm5iZiI6MTcxNTY0NTY1OSwicGF0aCI6Ii8xMTgwMzUyNzUvMzI1MDY3NzY4LTJhNmNhZmVhLTMxOGMtNDQxYy1iYTdmLWRhNjJlMWE5M2FmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMDE0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTMzNTVmZGY1YWZjZWJlZWJjNjk1OGFjOTExOTM5Zjc4YTM3Y2QyZGIyZGM4MjZjODAzOTgwYzlhZTNiZjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c2brdfjhMAREnAvhWTWXnsZqTFy5lKbhYC1YPHCOitI)
> 
> In the figure above, data 1 satisfies the relationship x3+x98 > x1+x2 from t1 to t100, while data 2 has moments when it does not satisfy this relationship (t5 - t100).
> 
> Purpose: Given the above two types of data, we can analyze which variables have a certain relationship in data 1. However, this relationship is not completely satisfied in data 2. The specific relationship does not need to be given, only the variable group is given.
> 
> It's possible that there are other variables with anomalies present simultaneously, but our aim is to capture sets containing (x1, x2, x3, x98), even if we may capture incorrect answers like (x1, x2, x3, x98, x5, x10) and (x11, x12, x13, x8, x5, x10).
> 
> Thank you for your attention to this matter. I look forward to hearing from you.
> 
> 中文描述： 问题描述：从数据中提取出具有某种线性关系的变量组。
> 
> 例如：有100个变量（x1 - x100），记录所有变量在100个时间戳（t1 - t100）的变量值，即为100*100的矩阵。并拥有满足某种关系的矩阵和不满足这种关系的矩阵，示意图如下：
> 
> ![image](https://private-user-images.githubusercontent.com/118035275/325068269-6c79ca8f-0673-4c8c-9769-9576adc522ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDU5NTksIm5iZiI6MTcxNTY0NTY1OSwicGF0aCI6Ii8xMTgwMzUyNzUvMzI1MDY4MjY5LTZjNzljYThmLTA2NzMtNGM4Yy05NzY5LTk1NzZhZGM1MjJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMDE0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmNhNTRjZTc5YWEyOTNlNGFlOTA4OTIwNDIzZDkyY2M2MWY5ZTM1ODU1NjAwMDg3ZTkwNDc1N2M0YjE4ZDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.23MY9BHQtIqv0IUbBKDHy_aJDQ7qhS03bgMSbSCf9f0)
> 
> 上图中，数据1在 t1 -t100 中均满足 x3+x98 > x1+x2 这一关系，而数据 2 有不满足该关系的时刻（t5 - t100）
> 
> 目的：给出上述两种类型的数据，能够分析出哪些变量间在数据1存在某种关系。而在数据2中不完全满足该关系，具体是什么关系可以不给出，只需给出变量组。
> 
> 可能还有其他变量同时存在异常，但我们的目标是捕获包含 (x1, x2, x3, x98) 的集合，即使我们可能捕获错误的答案，例如 (x1, x2, x3, x98, x5, x10 ）和（x11、x12、x13、x8、x5、x10）。
> 
> 感谢您的关注。 期待您的回复。

Hi, seems that you have added my WeChat and discussed it in detail. Feel free to contact me if there's any further progress.
