### ISSUE TITLE
How can we get the dataset NIPS-TS-GECCO and NIPS-TS-SWAN?

### ISSUE THREAD

**Issue by dongdong7876** [DAMO-DI-ML/KDD2023-DCdetector#38]
Hello, can you provide download addresses for the NIPS-TS-SWAN and NIPS-TS-GECCO datasets? Including NIPS_TS_Swan_train.npy, NIPS_TS_Swan_test.npy, NIPS_TS_Swan_test_label.npy, NIPS_TS_GECCO_train.npy, NIPS_TS_GECCO_test.npy, and NIPS_TS_GECCO_test_label.npy.

**Comment by yyysjz1997** [comment]
> Hello, can you provide download addresses for the NIPS-TS-SWAN and NIPS-TS-GECCO datasets? Including NIPS_TS_Swan_train.npy, NIPS_TS_Swan_test.npy, NIPS_TS_Swan_test_label.npy, NIPS_TS_GECCO_train.npy, NIPS_TS_GECCO_test.npy, and NIPS_TS_GECCO_test_label.npy.

Hi, we have provided a link of all the datasets. You could download NIPS-TS-SWAN and NIPS-TS-GECCO from [this URL](https://drive.google.com/drive/folders/1RaIJQ8esoWuhyphhmMaH-VCDh-WIluRR).🙂
