### ISSUE TITLE
关于损失的问题

### ISSUE THREAD

**Issue by shaieesss** [DAMO-DI-ML/KDD2023-DCdetector#41]
您好，我自己建立了一个类似的模型，发现学习出来的表征很多负数，即便在计算kl散度时有0.0001，torch.log也会存在nan的情况，而我看您的代码中好像没有用到太多的激活函数，请问是如何保证学习到的特征均为正

**Comment by yyysjz1997** [comment]
> 您好，我自己建立了一个类似的模型，发现学习出来的表征很多负数，即便在计算kl散度时有0.0001，torch.log也会存在nan的情况，而我看您的代码中好像没有用到太多的激活函数，请问是如何保证学习到的特征均为正

你好~为什么学习到的特征必须均为正呢？

**Comment by shaieesss** [comment]
> > 您好，我自己建立了一个类似的模型，发现学习出来的表征很多负数，即便在计算kl散度时有0.0001，torch.log也会存在nan的情况，而我看您的代码中好像没有用到太多的激活函数，请问是如何保证学习到的特征均为正
> 
> 你好~为什么学习到的特征必须均为正呢？

如果负的比较大，损失函数中加log里面0.0001作用不是很大，导致损失直接nan

**Comment by yyysjz1997** [comment]
> > > 您好，我自己建立了一个类似的模型，发现学习出来的表征很多负数，即便在计算kl散度时有0.0001，torch.log也会存在nan的情况，而我看您的代码中好像没有用到太多的激活函数，请问是如何保证学习到的特征均为正
> > 
> > 
> > 你好~为什么学习到的特征必须均为正呢？
> 
> 如果负的比较大，损失函数中加log里面0.0001作用不是很大，导致损失直接nan

那您可以尝试其他函数，或者将输入损失函数前添加一个合适的激活函数。我不懂您的需求，如果有更多细节可以加我联系方式，感谢关注

**Comment by shaieesss** [comment]
> > > > 您好，我自己建立了一个类似的模型，发现学习出来的表征很多负数，即便在计算kl散度时有0.0001，torch.log也会存在nan的情况，而我看您的代码中好像没有用到太多的激活函数，请问是如何保证学习到的特征均为正
> > > 
> > > 
> > > 你好~为什么学习到的特征必须均为正呢？
> > 
> > 
> > 如果负的比较大，损失函数中加log里面0.0001作用不是很大，导致损失直接nan
> 
> 那您可以尝试其他函数，或者将输入损失函数前添加一个合适的激活函数。我不懂您的需求，如果有更多细节可以加我联系方式，感谢关注

如何加联系方式

**Comment by yyysjz1997** [comment]
> > > > > 您好，我自己建立了一个类似的模型，发现学习出来的表征很多负数，即便在计算kl散度时有0.0001，torch.log也会存在nan的情况，而我看您的代码中好像没有用到太多的激活函数，请问是如何保证学习到的特征均为正
> > > > 
> > > > 
> > > > 你好~为什么学习到的特征必须均为正呢？
> > > 
> > > 
> > > 如果负的比较大，损失函数中加log里面0.0001作用不是很大，导致损失直接nan
> > 
> > 
> > 那您可以尝试其他函数，或者将输入损失函数前添加一个合适的激活函数。我不懂您的需求，如果有更多细节可以加我联系方式，感谢关注
> 
> 如何加联系方式

WeChat ID: yyysjz
