### ISSUE TITLE
What is patch size?

### ISSUE THREAD

**Issue by Wonderdch** [DAMO-DI-ML/KDD2023-DCdetector#6]
Thanks for your nice and concise work 😊

I was confused by the patch size in 3.2.2 when you introduce your multi-scale design.
Does patch size refer to the size of patches $P$ or the number of patches $N$?

If it stands for $P$, are there any differences between Patch-wise and In-patch in multi-scale experiment while Patch Size = [1]

**Comment by yyysjz1997** [comment]
> Thanks for your nice and concise work 😊
> 
> I was confused by the patch size in 3.2.2 when you introduce your multi-scale design. Does patch size refer to the size of patches P or the number of patches N?
> 
> If it stands for P, are there any differences between Patch-wise and In-patch in multi-scale experiment while Patch Size = [1]

Thanks for your interest in our work.  $\mathcal{N}$ is patch-wise representation and $\mathcal{P}$ is in-patch representation. Apart from that, we use $N$ to denote the number of patches, and $P$ to denote the size of
patches. Maybe the different fonts here are confusing you.

Also, if the patch size=[1], this means that for the patch-wise representation, it would degenerate into a self-attention of all timestamps inside a window, which would greatly increase the memory cost. And for in-patch representation, it will degenerate a per timestamp self-computation with itself.

Experiments have shown that when the dataset has a large anomaly ratio, it would be beneficial to include patch size=[1] in multi-scale design.
