### ISSUE TITLE
The test function never tests on the test data

### ISSUE THREAD

**Issue by GodofRap** [DAMO-DI-ML/KDD2023-DCdetector#9]
In the solver.py, the test() function doesn't have the model test on the test data. No self.model is called for test data.

**Comment by yyysjz1997** [comment]
> In the solver.py, the test() function doesn't have the model test on the test data. No self.model is called for test data.

We are very sorry about this, it is indeed a bug. We will upload the updated and validated code right away, and the results can be matched to those in the paper. Many thank you for the issue!
